version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: server/afterInstall.sh
      timeout: 120
      runas: ubuntu
#  ValidateService:
#    - location: ./codedeploy/validate.sh
#      timeout: 120
#      runas: ubuntu