version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu/codedeploy/*
    mode: 777
hooks:
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu