spring:
  profiles:
    active: "aws"
  main:
    banner-mode: "off"

---
spring:
  profiles: aws
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}/${DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

cloud:
  aws:
    region: ${AWS_REGION}
    profile: ${AWS_PROFILE}
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    s3:
      bucketname: ${S3_BUCKET_NAME}