spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}/${DB_NAME}?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

cloud:
  aws:
    region: ${AWS_REGION}
    profile: ${AWS_PROFILE}
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    assumeRoleARN: arn:aws:iam::482505208893:role/EC2-CSYE6225
    s3:
      bucketname:${S3_BUCKET_NAME}



