name: Master Branch Pull Request
on:
  pull_request:
    branches: master
jobs:
  build:
    name: Build and run Units & Integrations Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.4
      - name: Build with Maven
        run: mvn -B package --file pom.xml
